### PR TITLE
Update best-practice-security.md

### PR DESCRIPTION
**Pull request by machito**
Update number of packages Helmet provides in the "Use Helmet" section.

### CODE REVIEW

**Comment by wesleytodd** [comment]
To be honest I would rather link out to their docs than have to keep updating these kind of references.  Maybe just saying "a number of smaller middleware"?

**Review by dougwilson — CHANGES_REQUESTED** [review]
I agree that it should just probably not have the exact number here long term. But at least even for this PR, the `nine` should be replaced with 14, not appear crossed out on the website.

**Comment by machito** [comment]
@wesleytodd @dougwilson Thanks for the feedback. I've updated the PR.

**Review by wesleytodd — APPROVED** [review]

**Comment by machito** [comment]
@dougwilson Waiting on your approval here.

**Comment by wesleytodd** [comment]
Hey @machito, no need to take more of @dougwilson's time.  If you can just squash down your PR to one commit I will go ahead and merge it.

**Comment by dougwilson** [comment]
I apologize I was away. Yes, @wesleytodd approval is enough; he doesn't have to wait for me if he feels like my comments were addressed. I will approve it now anyway since I'm back. @wesleytodd feel free to dismiss my review here in the future if you feel the changes made reflect my asks 👍

**Review by dougwilson — APPROVED** [review]

**Pull request merged**
