### PR TITLE
feat: add color to inline code

### PR DESCRIPTION
**Pull request by bjohansebas**
To improve accessibility, a color is added to the inline code to create contrast with the rest of the content.

image
image

### CODE REVIEW

**Comment by carlosstenzel** [comment]
set color at beginning of file, in var

**Comment by bjohansebas** [comment]
@carlosstenzel done

**Review by UlisesGascon — APPROVED** [review]
LGTM! Great improvement!

**Comment by bjohansebas** [comment]
I would like to add `line-height: 28px;` throughout the page, as I feel the paragraphs are too close together.

**Pull request merged**
