### PR TITLE
[docs]: Routing - `timeLog` not defined

### PR DESCRIPTION
**Pull request by gregfenton**
Either have a function named `timeLog` or reword the last sentence of the page to remove the use of that name.

### CODE REVIEW

**Comment by crandmck** [comment]
This looks right to me, but I'd like someone to confirm.

**Review by UlisesGascon — APPROVED** [review]
LGTM! Thanks @gregfenton, this improves the readability 👍

**Review by crandmck — APPROVED** [review]

**Comment by crandmck** [comment]
The tests were failing because two lines of example code ended with colons. By convention, docs don't terminate code lines with colons.  I edited the fork/branch directly so we can land this.

**Comment by gregfenton** [comment]
Interesting that tests were failing because of valid code  😊

@crandmck Sorry for the trouble, and thank you for the fix.  If there's a CONTRIBUTIONS set of instructions I missed, apologies for that.

**Comment by crandmck** [comment]
No worries @gregfenton  Thanks for the contribution!
See https://expressjs.com/en/resources/contributing.html#collaborators-guide.
For semicolon usage, https://standardjs.com/rules#semicolons .

**Comment by gregfenton** [comment]
Cool, thanks for that!

Of course, this means that "fly by edits via GitHub UI" like I did are ... not inline with those standards.  My bad.

Cheers.

**Pull request merged**
