### PR TITLE
Remove some community resources

### PR DESCRIPTION
**Pull request by bjohansebas**
As we discussed here https://github.com/expressjs/discussions/issues/258, some of the recommended resources on the page are no longer used by the community. Therefore, they will be removed so they are no longer recommended while we look for new options from a new community.

### Notes:
- I can only perform the removal in Spanish and English since those are the languages I am familiar with.

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Review by IamLizu — COMMENTED** [review]
I am mostly okay with this. However, I would like "GitHub Discussion" be added as the community place for support.

**Comment by bjohansebas** [comment]
@IamLizu If the other TC members agree, I’d be happy to add "GitHub Discussion" as a place for support.

**Comment by crandmck** [comment]
Thanks for this @bjohansebas, I've been wanting to do this for some time!

Yes, please do add a link to https://github.com/expressjs/discussions.  

I see in https://github.com/expressjs/discussions/issues/258 there was discussion of adding the Slack channel.  I'd vote in favor of that, but that can be done in another PR; no need to hold up this one.

> I can only perform the removal in Spanish and English since those are the languages I am familiar with.

That's understandable, however, I'd like to ask that we try to keep all the langs in sync as much as possible.  One does not need to read the language to delete the sections in question. Since the content is well-structured, simply do this:
1. For Gitter, remove the section with the link to `https://gitter.im/..` including the header.
2. For Mailing list, remove the section with the link to `https://groups.google.com/..` including the header.
3. For IRC, remove the section with mention of `#express` and `freenode` including the header.

@bjohansebas Can you please try to do that?  If you run into difficulty, please comment here and I'll try to help.

**Comment by bjohansebas** [comment]
@crandmck Okay, I'll make the changes tomorrow. However what text should I use for GitHub Discussions?

**Comment by bjohansebas** [comment]
@crandmck I've noticed there are references to the wiki on GitHub. Should I also remove those links?

**Comment by crandmck** [comment]
The only links to the wiki I see are in "Moving to Express 4".  We can leave those for now.  If/when we decide to delete the wiki, we should do a thorough review of the content there to determine what needs to move into the docs and what can be simply deleted.

**Pull request merged**
