### PR TITLE
Remove vulnerable template engines

### PR DESCRIPTION
**Pull request by iamarpitpatidar**
No longer Maintained and have critical vulnerabilities (DDOS, Injection, etc)

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@iamarpitpatidar [vuexpress](https://github.com/vuexpress/vuexpress) hasn't had commits or releases in a long time. So, it makes sense to remove it. But removing [express-vue](https://github.com/express-vue/express-vue) does not make sense to me as there have been commits and releases.

**Comment by iamarpitpatidar** [comment]
> [vuexpress](https://github.com/vuexpress/vuexpress) hasn't had commits or releases in a long time. So, it makes sense to remove it. But removing [express-vue](https://github.com/express-vue/express-vue) does not make sense to me as there have been commits and releases.

@aravindvnair99 even tho it has recent releases but both of them have critical vulnerabilities and I don't think express js being one of the most used framework should include anything like that in its <strike>docs. </strike>(EDIT: Resources)
Once they fix the critical one we can always add them back

**Comment by aravindvnair99** [comment]
> @aravindvnair99 even tho it has recent releases but both of them have critical vulnerabilities and I don't think express js being one of the most used framework should include anything like that in its docs. (EDIT: Resources)
> Once they fix the critical one we can always add them back

@iamarpitpatidar I noticed you started an issue tracker at https://github.com/express-vue/express-vue/issues/263 as well. But you haven't provided details on what are the vulnerabilities you noticed or any audit information, etc. I do agree their [dependencies are outdated](https://david-dm.org/express-vue/express-vue). What I feel is we should wait for them to respond to your issue tracker. If it continues to be inactive, then makes sense to me to remove it. You could also help by sending them a PR with fixes.

**Comment by iamarpitpatidar** [comment]
@aravindvnair99 I agree but if you look at the issues history, same issues has been created on `11 Dec`, `17 Sep` and so on. I guess that's a good indication. But still we could wait like another week for them to respond.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 I agree but if you look at the issues history, same issues has been created on `11 Dec`, `17 Sep` and so on. I guess that's a good indication. But still we could wait like another week for them to respond.

Yes @iamarpitpatidar, but better to wait for their response. The other one you wanted to remove makes sense to me.

Also, you can leave this PR open though so that other members of Express can take a look and pitch in. What I mentioned is just my opinion. Can be closed if they continue being active. Reopening PR.

**Comment by dougwilson** [comment]
I agree, unless there is evidence the issue has been brought up with `express-vue` before that issue, we have to assume that until you alerted the project, the project was not aware of the problem. I think at least giving a week to response to an issue in their tracker is the minimum we can do, as most of these projects are open source and folks run them on their free time, and give them aware for free.

It would also seem this removes both Vue.js engines from the template list, so even more reason to give them some time to address the issue.

**Comment by iamarpitpatidar** [comment]
@dougwilson I think now its enough time both engines have been notified but still no repsonse. I say the best is to remove the engines untill they fix it or we have a new one.

**Review by aravindvnair99 — APPROVED** [review]

**Review by dougwilson — APPROVED** [review]

**Comment by dougwilson** [comment]
Yea, I see there is still no response to any of the opened issue or other activity in the repos.

**Pull request merged**
