### PR TITLE
create resources page for open source projects

### PR DESCRIPTION
**Pull request by klyburke**
@dougwilson I'm creating this PR in response to our [discussion](https://github.com/expressjs/discussions/issues/64) about a resources page for open source projects or applications using Express

Let me know what you think, and feel free to edit.

Thanks!

### CODE REVIEW

**Comment by crandmck** [comment]
It looks fine to me, except one small nitpick.  The URL for "Edit the markdown file" should be `https://github.com/expressjs/expressjs.com` not `https://github.com/strongloop/expressjs.com`.  It was moved out of the strongloop org years ago! :-)

@dougwilson any input?

**Comment by klyburke** [comment]
thanks for reviewing @crandmck ! I updated the URL.

I was following the structure you have for the `books-blog` page. So that one may need to be updated.

**Comment by crandmck** [comment]
> I was following the structure you have for the books-blog page. So that one may need to be updated.

Oops! Thanks for pointing that out.... Slipped through the cracks!

**Comment by crandmck** [comment]
OK I fixed that old URL on `books-blogs`.

Also, I didn't notice before I landed your PR, but you didn't add the page to the `Resources` menu, so I went ahead and did that.  In case you're interested, for future reference, here's how to do it: https://github.com/expressjs/expressjs.com/commit/b8148d82905868c60f946d463ebe6c66650b4b6d#diff-8425cd5bb28d2c271546ea0c877480b1

nb. This is currently only in the English menu.  In theory, we should update all the localized menus as well, even though the page is not translated--it will fall back to the English version.... But that can wait for another day.

**Comment by klyburke** [comment]
@crandmck I see, thanks for making those fixes and for merging the PR!

**Pull request merged**
