### PR TITLE
added dinoloop framework to the list

### PR DESCRIPTION
**Pull request by ParallelTask**

### CODE REVIEW

**Review by dougwilson — APPROVED** [review]
Awesome 👍

**Comment by ParallelTask** [comment]
@dougwilson I have notified on pull request approval changes. just curious to know, are my changes merged to branch or do I need to do anything else to merge my changes into our project? I would just like the community know, a new library built powered by typescript and express. Let me know your thoughts :)

**Comment by dougwilson** [comment]
Yep, I approved it. Since the fork repo has been deleted I cannot merge it, though another member may be able to.

**Comment by ParallelTask** [comment]
@dougwilson When do I expect the official webpage of expressjs.com shows up my library in the list? Just excited to know

**Comment by dougwilson** [comment]
Since your fork repo has been deleted I cannot merge it, though another member may be able to.

**Comment by crandmck** [comment]
Sorry for the delay @ParallelTask. I was out for a while and got behind!

**Comment by ParallelTask** [comment]
Thanks for your support and kind heart. Also, do give a try to Dinoloop we are soon going to have an official website up by the end of July and some breaking changes too.

**Pull request merged**
