### PR TITLE
Sun icon missing everywhere except En Header - Add it

### PR DESCRIPTION
**Pull request by chrisdel101**
The sun icon was only added to English. Might as well add it to the entire site. 

Also moon icon was 2x size originally and was changed. Re-add the 2x since it looks better. 

Changes here should only be the addition of the sun icon to every header file.

### CODE REVIEW

**Comment by chrisdel101** [comment]
All the tests are failing.  Looks like ruby version error?
I've never had this happen here before. 

This PR should only be a single commit but those 5 merges are tacked on for some reason. Maybe it's related to those....
Looks like a ruby versioning error. Not even where to set this?

Edit: I see it's actually #1566

**Comment by crandmck** [comment]
#1566 was merged, but tests are still failing.  @chrisdel101  I wonder if a trivial commit to this fork/branch might re-run the tests so they would now pass?

**Comment by chrisdel101** [comment]
Seems fixed after a full re-merge with main.

**Review by carlosstenzel — APPROVED** [review]

**Review by crandmck — APPROVED** [review]

**Comment by crandmck** [comment]
Thanks again @chrisdel101 !

**Pull request merged**
