### PR TITLE
Make menu links "clickable" only on mobile devices

### PR DESCRIPTION
**Pull request by hacksparrow**

### CODE REVIEW

**Comment by dougwilson** [comment]
The `'ontouchstart' in document.documentElement` is still returning true on my laptop. Probably because it has a touch screen, like many computers these days. Any other way to detect mobile?

**Comment by hacksparrow** [comment]
Oh, should have thought about that! There are many ways to detect mobile, each with its pros and cons. Let me look for the best.

**Comment by hacksparrow** [comment]
@dougwilson, I have added a small lib to detect mobile devices, please take a look now.

**Comment by dougwilson** [comment]
LGTM

**Comment by crandmck** [comment]
Thanks @hacksparrow

**Pull request merged**
