### PR TITLE
feat: improve footer layout

### PR DESCRIPTION
**Pull request by bjohansebas**
- Add OpenJS Foundation logo
- Improve layout
- Add new links

Before:
- Desktop
before layout
- Mobile
mobile-before

After:
- Desktop
after layout
- Mobile: 
mobile-after

### CODE REVIEW

**Comment by UlisesGascon** [comment]
It feels much modern and fresh! Thanks for the proposal @bjohansebas!

One question... should the OpenJS logo be in the center in mobile?

Screenshot from 2024-07-28 12-48-20

**Comment by bjohansebas** [comment]
@UlisesGascon  yes, it should be centered; it’s fixed now.

image

**Comment by crandmck** [comment]
LGTM @bjohansebas 
I see you implemented it for en and es.  Could you please do the same for all the other languages?  

This highlights the need to separate layout from content, so changes like this wouldn't require modifying every language, but that's another story!

**Comment by bjohansebas** [comment]
@crandmck Ready, the new footer is now available in the other languages.

**Review by UlisesGascon — APPROVED** [review]

**Comment by crandmck** [comment]
Thanks @bjohansebas !

**Pull request merged**
