### PR TITLE
Fix app.listen calls doc

### PR DESCRIPTION
**Pull request by madarche**
Hello dear Express maintainers,

This PR does:
- Fix the fact that the "port" argument is optional
- Fix Node.js doc links
- Fix HTML id, an HTML id must be unique

### CODE REVIEW

**Comment by crandmck** [comment]
Thanks for the PR.  

It all looks good, except for changing the second heading from `app.listen(..)` to
```
server.listen([port[, host[, backlog]]][, callback])
```
All the other headings and the code blocks use `app`, and I'd like to maintain that convention.

I think if you just make that small change, it should be good to land.

**Comment by crandmck** [comment]
Closes #929.

**Comment by madarche** [comment]
I've fixed the erroneous replacement (sorry!) and rebased. Ready for your proof reading!

**Comment by crandmck** [comment]
LGTM, thanks!

**Comment by madarche** [comment]
Thanks @crandmck!

**Pull request merged**
