### PR TITLE
improve the translation of  'routing.md'

### PR DESCRIPTION
**Pull request by KevinHu-1024**
1. improve the translation of 'routing.md', in case of misunderstanding.
2. http://www.expressjs.com.cn/guide/routing.html
   This webpage need to be update.
   It's a very old version.

Thank you!

### CODE REVIEW

**Comment by crandmck** [comment]
Hi @KevinHu-1024 The site http://www.expressjs.com.cn/ is _not_ official Express documentation and is not connected to this repo in any way.  Actually, this is the first I've heard of it. 

The official Express docs are:
- Simplified Chinese: http://expressjs.com/zh-cn/ source at https://github.com/strongloop/expressjs.com/tree/gh-pages/zh-cn
- Traditional Chinese: http://expressjs.com/zh-tw/ source at https://github.com/strongloop/expressjs.com/tree/gh-pages/zh-tw

Please review the Chinese content on the official site, and if you notice any issues, you are welcome to open a new PR.

**Comment by crandmck** [comment]
Also, since we have the two more recent Chinese translations above, I realized that we need to delete the `zh-cn` docs.  These old docs are being published to http://expressjs.com/zh-cn/, but are not linked from the home page, as are the most recent translations noted above.  I'll open a PR to remove the old `zh-cn` docs.

**Comment by crandmck** [comment]
OK, I reopened this because I had assumed that your edits apply to the content at http://www.expressjs.com.cn/guide/routing.html, which is not connected to this repo.  However, if they also apply to http://expressjs.com/zh-cn/guide/routing.html and  http://expressjs.com/zh-cn/guide/using-middleware, please say so.

**Comment by KevinHu-1024** [comment]
Yes, they **apply** to the official Express documentation(they aimed at this repo). In fact, when I read the unofficial documentation, I noticed these issues.So I find the official Express documentation on github, and find there are also some inappropriate translation. Then I opened the PR.

P.S. To the **Traditional Chinese version**, I don't know the language habits of Taiwan/Hongkong and so on.So I couldn't check them.

I also just know that this is not the official website. Thank you!

**Comment by crandmck** [comment]
@KevinHu-1024 Thanks for the PR! Sorry about the misunderstanding.  Feel free to open more PRs if you find more problems.  Also, it would be great if you could comment in #533 general on the translation quality (or general issues).

**Pull request merged**
