### PR TITLE
Add join-io

### PR DESCRIPTION
**Pull request by coderaiser**
Added [join-io](https://github.com/coderaiser/join-io) express middleware.

### CODE REVIEW

**Comment by hacksparrow** [comment]
If I understand the use-case of this middleware, it is better accomplished with the help of task runners like `gulp`, `grunt` etc.

**Comment by coderaiser** [comment]
No, you could not achieve the same results with help of `gulp`, `grunt` etc.
`join-io` it's middle ware that joins files on a fly. No need to store joined file like task runners does this,
because `join-io` do it with help of [streams](https://github.com/substack/stream-handbook): it's open files and pipe them to `response` one-by-one, when everything is done, stream is closing.
`join-io` based on `readPipe` function of [files-io](https://github.com/coderaiser/files-io).

After prefix`/join:` names should be written of files that need to be combined .
This way:

``` html
<link rel="/join:/css/normilize.css:/css/style.css">
```

Minification could be enabled too. No need in intermediate step.
Everything is simple and transparent.

By the way [jsdelivr](http://www.jsdelivr.com/) works in similar way: [load Multiple files with a single HTTP request](https://www.maxcdn.com/blog/jsdelivr-better/).

**Comment by dougwilson** [comment]
I don't see why we can't just add it to the list (except for the fact that the Markdown looks wrong in the PR).

**Comment by coderaiser** [comment]
@dougwilson, what is wrong with markdown?

**Comment by jordonias** [comment]
@coderaiser I think he means the `"join-io"` after the url. Maybe a period at the end as well to be consistent.

**Comment by dougwilson** [comment]
Nevermind. I see the double quotes in there adds a title to the link. I've never seen that before, i.e. I was expecting it to look like the "Links" section in https://guides.github.com/features/mastering-markdown/

**Comment by coderaiser** [comment]
@jordonias @dougwilson  so I should remove double quotes and add period?

**Pull request merged**
