### PR TITLE
Fixed document Error.

### PR DESCRIPTION
**Pull request by yiyu0x**
In Chinese document, **res.sendFile** not has **()**.

### CODE REVIEW

**Comment by jonchurch** [comment]
This typo is also in several other translations apparently.

https://github.com/expressjs/expressjs.com/blob/8225868d73753107fdb03de48f9929d34ed01e1c/es/guide/routing.md#L265

https://github.com/expressjs/expressjs.com/blob/8225868d73753107fdb03de48f9929d34ed01e1c/fr/guide/routing.md#L266

https://github.com/expressjs/expressjs.com/blob/8225868d73753107fdb03de48f9929d34ed01e1c/zh-cn/guide/routing.md#L265

And I'd assume perhaps the rest of the localizations, but these are the only ones I checked.

**Comment by yiyu0x** [comment]
@jonchurch Thanks you, I've fixed the other typos.

**Comment by yiyu0x** [comment]
@jonchurch Can you merge this PR ?

**Comment by jonchurch** [comment]
@yiyu0x I don't have merge permissions. Someone will come along and merge this at some point though 👍

**Pull request merged**
