### PR TITLE
add router mergeParams option to docs

### PR DESCRIPTION
**Pull request by makenova**
@dougwilson , in reference to this issue visionmedia/express#2257.
The wording needs work but, the `mergeParams` option is useful and should be documented.

### CODE REVIEW

**Comment by dougwilson** [comment]
You really mean in reference to #169 which has been here for a bit :) I don't actually have access to this repo... @jonathanong @defunctzombie

**Comment by makenova** [comment]
You are correct, I should have check the open issues first. Thanks!

**Comment by jonathanong** [comment]
@visionmedia can you add @dougwilson here?

**Comment by sixlettervariables** [comment]
+1, I completely missed this and reimplemented the wheel (poorly) this morning...

**Comment by makenova** [comment]
That's more concise but I'm not sure I would understand it if I didn't already know what it did.
I do prefer it over what I currently have.

**Comment by hacksparrow** [comment]
Documented - 71fc1620632f06a087f2be7211b43b4ab1e1ce0d

**Pull request closed without merging**
