### PR TITLE
Fix grammar in res.sendFile documentation

### PR DESCRIPTION
**Pull request by OliverBalfour**

### CODE REVIEW

**Comment by crandmck** [comment]
I don't think this will work because the string `'Sorry! You can't see that.'` is single-quoted and the apostrophe is also a single quote.  You need to either escape the apostrophe or enclose the string in double-quotes `"`.

**Comment by hacksparrow** [comment]
@Tobsta can you make the change as suggested by @crandmck? I can land it, if you do.

**Comment by OliverBalfour** [comment]
Just updated, sorry about that. Didn't notice at all.

**Comment by hacksparrow** [comment]
Thanks @Tobsta

**Pull request merged**
