### PR TITLE
Copy 5x documentation files

### PR DESCRIPTION
**Pull request by RamirezAlex**
This is related to: https://github.com/expressjs/express/issues/3913

Includes: 
* copy `en/4x` --> `en/5x`
* copy `_includes/api/4x` --> `_includes/api/5x`
* copy `_layouts/4x-api.html` --> `_layouts/5x-api.html`
* add link in `header/header-en.html` to 5.x (RC) documentation

@dougwilson Could you please review and also provide me with more information or examples of what should edit on the entries related to the change log (https://github.com/expressjs/express/blob/5.0/History.md) ? Thank you.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @RamirezAlex, good work on getting this started!  I think we probably want to start by pulling this into a `5.0` branch so we can make additions and changes as we get ready to release.  Or do people think we should start with these docs as "beta" docs and merge it as we go?  That might be helpful for people to follow along and contribute updates we might miss.

Also @RamirezAlex, just because no one has commented doesn't mean it has been ignored.  @crandmck is one of the thumbs up, and he is the primary contact for maintaining this.  It just takes time to get to all the PR's and work being done in Express :)

**Comment by crandmck** [comment]
Sorry I've been MIA for a bit...

I think it will be easier if people can see how the 5.x docs are evolving, i.e. not in a branch--which wouldn't be visible on the site, only on GH (or if you built and ran the branch locally on Jekyll).  

This PR adds the API docs under "5.x RC":
Screen Shot 2019-06-10 at 8 17 45 PM

Assuming "RC" is the right rubric, I think we can land this and take it from there. 

One small gotcha: Since this PR was opened, 4.17 was released with a couple new functions - see #1043 ... So, we'll just need to add those updates.  IMO it could be done in this PR (best), or even after merging (as long as we don't forget!).  Thoughts?

**Comment by dougwilson** [comment]
Currently 5.x is alpha, so it should probably note alpha in the heading. And I agree with landing it on master to make it available on the site as it's being worked on -- just it's existence should help provide exposure to usage more than it's getting now.

**Comment by crandmck** [comment]
Cool... So, @RamirezAlex if you would change the heading to `5.x (alpha)`, then I will merge this, and add the stuff from #1043.

**Comment by RamirezAlex** [comment]
Thank you all for the guidance here. So, @crandmck I changed the heading to `5.x (alpha)` as requested and removed the WIP tag from the PR. However, it seems like `Travis` is not liking the semicolons in the doc files. Do we have recent updates to linter rules for this? Should I go and remove those semicolons to satisfy the linter or how do we proceed? I can do it, I just want to make sure. Thank you again.

**Comment by RamirezAlex** [comment]
Ignore it @crandmck, I found out that StandardJS was recently added, so I applied the fixes accordingly. :)

**Comment by RamirezAlex** [comment]
Thank you for all the feedback @crandmck, I already applied the changes so when you have a chance please review it and let me know whether there are next steps or this is Ok.

**Comment by crandmck** [comment]
@RamirezAlex Sorry for the delay.  I will try to review this in the next day or so.

**Comment by crandmck** [comment]
Thanks for the contribution, @RamirezAlex !

**Pull request merged**
