### PR TITLE
Adding option wrapper documentation

### PR DESCRIPTION
**Pull request by franciscop**
Following on https://github.com/expressjs/express/issues/3150 , I open this PR to add documentation regarding the options parameter factory recommendation.

### CODE REVIEW

**Comment by crandmck** [comment]
@hacksparrow  It looks OK to me, but can you please review this?

**Comment by crandmck** [comment]
@hacksparrow ping...

**Comment by dougwilson** [comment]
The docs are pretty bare-bones but the content is correct, imo, so at the very least it is a good jumping off point to merge and fill out further.

**Comment by hacksparrow** [comment]
Will land this after making some small changes.

**Comment by franciscop** [comment]
What kind of documentation can/should I provide? I have no problem on expanding on anything to make this more complete.

**Comment by hacksparrow** [comment]
@franciscop based on your input, I have updated the doc - http://expressjs.com/en/guide/writing-middleware.html. We now have a section titled "Configurable middleware", at the bottom. Thanks for the PR!

**Pull request closed without merging**
