### PR TITLE
Make it more clear

### PR DESCRIPTION
**Pull request by davidgatti**
Went from, what is going on I have no idea what I'm reading, to: OK, now it is super clear. Especially for non English speaking people :)

### CODE REVIEW

**Comment by dougwilson** [comment]
You can also set it to a number, a string, or an array, all of which are non-false. The value true is only one possible way to trigger the behavior. I think if you are going to change it, you need to enumerate what all the possible non-false values are.

**Review by dougwilson — CHANGES_REQUESTED** [review]
See comment

**Comment by crandmck** [comment]
Also, "...will results in..." is incorrect grammar.  I would suggest either:
- "Setting `trust proxy` to (...specify values...) results in the following changes:"
- "If `trust proxy` is not `false` then:"

**Comment by davidgatti** [comment]
OK, sounds like a plan :)

**Comment by crandmck** [comment]
@davidgatti ping...

**Comment by davidgatti** [comment]
Pong :) 

I know, so much poop going on :( will try to make it happen this weekend.

**Comment by davidgatti** [comment]
@dougwilson I'm so sorry this simple thing took so much time, but I mad the change based on your suggestion. 

@crandmck, is the grammar OK?

**Comment by dougwilson** [comment]
You missed that you can also set to a number :)

**Comment by dougwilson** [comment]
(A non-falsy number, so zero does not enable, but 1, 2, 3, etc. all enable it for that number of hops).

**Comment by dougwilson** [comment]
Now that I just re-read that secion, we can really just remove the first sentence and be done with it, imo

**Comment by davidgatti** [comment]
🤣🤣🤣

**Comment by davidgatti** [comment]
There you go ;)

**Comment by crandmck** [comment]
Often, the simplest solution is the best...thanks! :-)

**Comment by davidgatti** [comment]
Always :D

**Pull request merged**
