### PR TITLE
Change tree files `express myapp` on generator.md

### PR DESCRIPTION
**Pull request by isRuslan**
Shellfy docs :v:

Change skeleton image to skeleton files tree.

### CODE REVIEW

**Comment by crandmck** [comment]
@isRuslan Could you explain your rationale for this change?  The content appears to be the same, but you've just replaced the image with text.  Why is this preferable?

**Comment by isRuslan** [comment]
@crandmck Yes, practically the same. It is a matter of yours taste, but the reasons are:
- Common content style on a page (text + shell snippets);
- Shell `tree` file output looks more common for everybody than Finder window. Not-OS-X users will not be frustrated about what this window is;
- count of directories | files (not so important, but pleasant).

Just one opinion.

**Comment by hacksparrow** [comment]
Makes sense.

**Comment by crandmck** [comment]
WFM.

**Pull request merged**
