### PR TITLE
Added Doug's video on homepage

### PR DESCRIPTION
**Pull request by iamropo**
This PR adds Doug's video on the homepage for all the languages.

Preview:

Desktop
screen shot 2017-01-29 at 5 23 06 pm

Tablet
screen shot 2017-01-29 at 5 23 22 pm

Mobile
screen shot 2017-01-29 at 5 23 40 pm

### CODE REVIEW

**Comment by hacksparrow** [comment]
LGTM.

Btw, @iamropo is my lil bro. He implemented the changes under my guidance.

**Comment by dougwilson** [comment]
Haha, awesome! Welcome @iamropo ! When I first saw the PR popup, I was like wow this person put a lot of work into this and it looks very well done. LGTM

**Comment by iamropo** [comment]
Thank you so much, @dougwilson.

**Comment by crandmck** [comment]
Nice! TYVM, @iamropo !

**Comment by iamropo** [comment]
Welcome @crandmck.

**Pull request merged**
