### PR TITLE
Update community page

### PR DESCRIPTION
**Pull request by bjohansebas**

### CODE REVIEW

**Review by UlisesGascon — COMMENTED** [review]
I think that we follow alphabetical order if I am not mistaking here :thinking:

**Comment by bjohansebas** [comment]
I don't think so, but if you want it to be in alphabetical order, should it be by username or by first name?

**Comment by blakeembrey** [comment]
> if you want it to be in alphabetical order, should it be by username or by first name?

IMO probably username? That way you can just "sort lines" in your editor.

**Comment by bjohansebas** [comment]
ping

**Pull request closed without merging**
