### PR TITLE
Add: companies using express

### PR DESCRIPTION
**Pull request by Knighton910**
Added Companies using expressjs :white_check_mark:

### CODE REVIEW

**Comment by Knighton910** [comment]
screen shot 2016-03-17 at 2 18 42 pm

**Comment by crandmck** [comment]
Thanks, this is great!  I'll make a few fixes after I merge (some broken links and "Express" should be capitalized).

**Comment by Knighton910** [comment]
+1 `Thanks, this is great! I'll make a few fixes after I merge (some broken links and "Express" should be capitalized).` :100:

**Comment by Hanzig** [comment]
Why does Exove not fit it? :)

**Pull request merged**
