### PR TITLE
Adding a page to "Advanced topics" menu for process managers

### PR DESCRIPTION
**Pull request by crandmck**
Comparing PM2, Forever, and StrongLoop PM per #377.
@altsang

### CODE REVIEW

**Comment by maxx0r** [comment]
The PM2 part says you need to start with
`pm2 app.js`
which should be 
`pm2 bin/www`

per express4.

**Comment by crandmck** [comment]
Actually, it says `pm2 start app.js` but your suggestion might be preferable.  

But I think that command presumes that you've created the app with the standard layout as the express-generator.  

As I look at the other sections, they are not consistent.  Thoughts @dougwilson ?

**Comment by maxx0r** [comment]
Can't quite remember how i started it, but i think it was through the generator. Maybe it's a good idea to put that as a hint there, so people can at least check it when the regular command fails (pm2 start app.js just fails with sigint)

**Comment by crandmck** [comment]
I agree adding some more context in that page makes sense.  

I just tested it, and`pm2 start app.js` does work if you create the app manually following instructions in [Installing](http://expressjs.com/en/starter/installing.html) and [Hello World](http://expressjs.com/en/starter/hello-world.html).  Admittedly, that might not be "best practice" but it does work.

Also `pm2 start app.js` is the command shown in the pm2 instructions at https://github.com/Unitech/pm2.

**Comment by dougwilson** [comment]
Sorry, forgot to reply here :) The issue woupd be how detailed this should be, which is a balancing act. Both are correct: bin/www is for the generator and app.js for thr single file hello world.

**Comment by crandmck** [comment]
Thanks... My preference would be to just add a short note in each section stating that the example command (e.g. `pm2 start app.js`) is for a simple app where`app.js` is the main script and if the app is creatd w generator, you would use a different command.

Created #852 to track this.

**Comment by maxx0r** [comment]
Thanks for picking this up guys, this is encouraging for users like me  to mention fixes like these instead of keeping the fix for themselfs and let others suffer :)

**Pull request merged**
