### PR TITLE
Improving example for PostgreSQL

### PR DESCRIPTION
**Pull request by vitaly-t**
Replacing the core `pg` example with the modern `pg-promise`.

### CODE REVIEW

**Comment by bajtos** [comment]
@crandmck @ritch I am not sure who is reviewing pull requests for expressjs.com. I have assigned thi PR to Ritch, feel free to reassign as appropriate.

**Comment by crandmck** [comment]
@bajtos Usually either I do; for more technical items @dougwilson or @hacksparrow does.  But if @ritch can review this, that's fine too.  Note that this PR came in the context of  https://github.com/strongloop/expressjs.com/issues/479.

**Comment by dougwilson** [comment]
This seems fine, especially since looking at the old example, it was terrible. This is already an improvement, regardless of the change from callbacks to promises.

**Comment by vitaly-t** [comment]
> This is already an improvement, regardless of the change from callbacks to promises.

A longer example could show how nicely it works with ES6 generators also, but I tried to keep the example as simple/small as possible. I think it's modern enough :)

**Comment by crandmck** [comment]
Given Doug's comment above, I merged this.  Thanks @vitaly-t!

**Pull request merged**
