### PR TITLE
Fix for issue #116.

### PR DESCRIPTION
**Pull request by ghost**
All pages should be clear and readable on all devices now. Removed quite a lot of absolute positioning, and decided to hide menus on smaller screens.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Please remove the built files from this PR

**Comment by defunctzombie** [comment]
Awesome. Just squash these commits into one and I can merge.

**Comment by defunctzombie** [comment]
BTW. ping me when you squash cause github doesn't notify me when commits change (that is why the delay in revisiting this issue)

**Comment by ghost** [comment]
Squashed, created a new branch and pull request.

Sorry for all the hassle, I'm new to this GitHub stuff :)

Let us know if I messed anything else up lol.

**Pull request closed without merging**
