### PR TITLE
Add search functionality to the documentation

### PR DESCRIPTION
**Pull request by phrawzty**
Hello Express maintainers!

This PR adds a search bar in the header. This functionality is provided by [DocSearch](https://community.algolia.com/docsearch/documentation/), which is a community project to add search to documentation all across the web, for _free_. 👍 Disclaimer: I help maintain the project, and am also employed by the company (Algolia) that made it - but DocSearch itself is fully [OSS](https://github.com/algolia/docsearch) (MIT). For reference, DocSearch powers the search on lots of other OSS and community projects already, including React, Jekyll, Laravel, and more.

Basically, we scrape your site, and according to a relatively straightforward set of rules, turn that scrape into an index that DocSearch can access (your config is [right here](https://github.com/algolia/docsearch-configs/blob/master/configs/expressjs.json)). From there, all you need to do is add an input box and a little JS - now you've got fast, accurate search across all your docs! 🎉 

It looks like this:
image

The translations are indexed too!
image
To be fair, in this PR I only modified the `en` and `fr` includes, but all of your translations are available. 😄  I'd be happy to make the remaining modifications if somebody would be kind enough to help me with proper translations for "Search the docs", hehe.

The default DocSearch CSS is minimalist and fits fairly well with your palette. That said, you're more than welcome to style it any way you like (the DocSearch docs have more details). I'd be glad to help you with this as well, if you like. (Caveat: I'm not a web designer, but I try my best!)

I sincerely hope that you find this feature useful. If you have any questions, comments, or concerns, please don't hesitate to let me know. In any case, thanks for all your diligent work over the years on the framework - keep up the great work!

### CODE REVIEW

**Comment by hacksparrow** [comment]
Is it mobile compatible?

**Comment by phrawzty** [comment]
> Is it mobile compatible?

Great question! In fact, we just [merged](https://github.com/algolia/docsearch/pull/197) a responsive version of our default CSS _today_. 😄

I'm not sure how to work effectively within the context of your site in particular (again, not a web designer, haha). You have some clever JS that plays with the menu items when the screen reaches < 900px width, so in order to test it locally I had to put the search bar just outside of `navmenu` (in order to avoid a disappearing act), but here's a rough idea:

image

To be clear, we're just talking about CSS here, which means it can be rendered any way you might like. Take React for example:

image

If you're interested in integrating DocSearch on your site, it may be possible to get some web dev resources allocated on our side as part of our general OSS contribution efforts. 👍

**Comment by dougwilson** [comment]
I am interested in seeing this become reality. I am curious on one aspect I see in the diff: what is that API key for? I assume it's just something that would restrict the usage to expressjs.com , is that right?

**Comment by phrawzty** [comment]
> what is that API key for?

You assume correctly. It's a key that allows read-only access to your index. It's in the clear because, well, if somebody else wanted to search your documentation, we'd be OK with that. 😉

> I am interested in seeing this become reality.

Great - me too, so let's do it! What can I do to help?


For the sake of completeness, we've got an official "snippet" that we generally send out to people via email - I'll reproduce it here:

---

Hi there,

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page
```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
```
```
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '7164e33055faa6ecddefd9e08fc59f5d',
  indexName: 'expressjs',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["lang:$LANG"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input if you don't have any yet, and update the `inputSelector` value in the code snippet to a CSS selector that targets your input field.

- Replace `$LANG` with the language you want to search within, contextually.
   The list of possible languages is hardcoded in the config; as of today you have: de, en, es, fr, it, ja, ko, pt-br, ru, sk, tr, uk, uz, zh-cn, zh-tw

  For example if you want to search in German, just specify: `'facetFilters': ["lang:de"]`

- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/expressjs.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

---

**Comment by crandmck** [comment]
I think this is a great addition to the site!  Thanks @phrawzty for the PR!

I've been out for a couple of weeks, so I'm just catching up on GH notifications, and I haven't had a chance to review it yet. I'll take a look ASAP, and--assuming that @hacksparrow approves--I'll land it since Doug has already approved it above.  If anyone else has an objection, please LMK.

**Comment by hacksparrow** [comment]
Great addition, indeed. I will do some mobile testing (and editing, if necessary) and land it.

**Comment by phrawzty** [comment]
Hi all! I'm glad that you're interested. I'd like to make it clear that this PR needs work. 😄 The modifications have only been made to the English and French pages, for example, and the search bar disappears when you enter responsive mode (which probably isn't what you want).

That said, the backend is set up and the search experience is totally functional, so you'll be good to go once you're happy with the UI.

**Comment by hacksparrow** [comment]
@phrawzty I have been working on mobile view and encountered a problem. In the mobile screen dimensions, merely clicking on `#docsearch-input` redirects the browser to `/undefined`.

Can you find out what's happening in your lib and fix it? With that done, we should have a mobile search soon.

**Comment by phrawzty** [comment]
👆 cc @s-pace and @maxiloc 👆

**Comment by maxiloc** [comment]
Hi,

I tracked down the issue. It's not coming from the docsearch code.

it's related to the `dropit` event that has redirections and is somehow misbehaving with the input:
https://github.com/expressjs/expressjs.com/blob/616bf2f7ab54c323fbc4568dbf268193a58faa06/js/app.js#L204
https://github.com/expressjs/expressjs.com/blob/616bf2f7ab54c323fbc4568dbf268193a58faa06/js/app.js#L222

**Comment by s-pace** [comment]
@hacksparrow Could you help me to reproduce it.
While this does happen? After results are displayed within the dropdown? Did you have a specific query? Do you have a screenshot?
I want to know if it is an UI issue or that we scrap an empty element (The latter assumption sounds more likely)

**Comment by hacksparrow** [comment]
Thanks guys, will take a look at it.

**Comment by hacksparrow** [comment]
I am going to be away for a week or so, if anyone wants to take a look at it in the mean time, please do.

**Comment by crandmck** [comment]
I've been out and haven't had a chance to look at this more closely... @hacksparrow did you sort out the issue you were seeing?

**Comment by hacksparrow** [comment]
@crandmck taking a look at it today.

**Comment by hacksparrow** [comment]
@phrawzty @maxiloc was anything changed in the library CSS? The menu which used to work on mobile devices now seems to be broken. 

Btw, the input box is being repositioned.

screen shot 2018-01-20 at 11 47 34 pm

Having said that, the search menu is still being truncated even after all position related styles were removed.

screen shot 2018-01-20 at 11 51 56 pm

**Comment by phrawzty** [comment]
Hello. Unfortunately, I'm no longer involved with the project.

Good day.

**Comment by crandmck** [comment]
@hacksparrow Do you want to try and fix the issues so we can land this PR?  I may be able to work on it, but haven't had much time lately.  It would be a shame to close this and not to get this functionality...

**Comment by hacksparrow** [comment]
Thanks @phrawzty 

@crandmck the fix has to done in the Algolia lib. Since it is an external lib, not sure how easy it is going to be or how long it is going to take.

Developing one ourselves might be an easier option, IMO.

**Comment by s-pace** [comment]
👋  @hacksparrow ,

Except [this main change](https://github.com/algolia/docsearch/pull/197/files), no other main modifications have been made regarding the CSS library. We have only updated dependencies.

Would be happy to jump on a ongoing PR in order to have a look myself, Could you provide us a link pls?

**Comment by s-pace** [comment]
Can be closed since expressjs/expressjs.com#1039 has been merged 🚀 

Thanks 🙏

**Comment by dougwilson** [comment]
@s-pace thanks for noticing this stale PR. Closing now, thanks again ❤️

**Pull request closed without merging**
