### PR TITLE
Losslessy optimize images with ImageOptim

### PR DESCRIPTION
**Pull request by rjmunro**

### CODE REVIEW

**Comment by crandmck** [comment]
I'm not familiar with ImageOptim, but it sounds great in theory..I'll try to find time to download this fork and run it locally to confirm that all the images still work properly.  

If so, then I don't see any reason not to land this.  

@dougwilson @hacksparrow sound OK?

**Comment by dougwilson** [comment]
No reason I can think of.

**Comment by rjmunro** [comment]
@crandmck @dougwilson Is there anything I should be doing to get this merged?

**Comment by crandmck** [comment]
I confirmed that the fork/branch runs fine locally, and I can see that all the changes are confined to image files, so I'll go ahead and land it.

Thanks @rjmunro

**Pull request merged**
