### PR TITLE
Update to latest jade/deps

### PR DESCRIPTION
**Pull request by knownasilya**
The purpose of this is to make it super easy to contribute to the docs, which will only promote express all the more.

I've moved over from `make` to `gulp`, which will work on any os. I've also update to the latest jade, to be current to the docs. Also updated the `readme`, which includes one less for building. 

Note: In the future I'll probably setup a watch/reload on template change.

### CODE REVIEW

**Comment by tj** [comment]
make works on any os as well. the jade defined in ./package.json should work just fine you just need to `npm install`. I don't want to use any of these js build tools, there's a new one every week, it'll just keep changing

**Comment by defunctzombie** [comment]
-1000 for gulp. I am all for updating to latest jade but gulp and grunt are silly tools that just incubate millions of plugins for no reason.

Can we get an updated PR with just updated deps and none of the other stuff.

**Comment by knownasilya** [comment]
I gotta say though, `make` didn't work for me, but only gave me trouble.. It wouldn't build if there were no changes at the top level jade files.

The purpose isn't to use a new build system, but to make it easy to contribute. Everyone knows javascript, and jade uses javascript, so does express. It is assumed that anyone that is going to contribute will know javascript. If the build file doesn't work, then they have to fiddle with `jade` directly or learn `make`.. and it doesn't work properly.

**Comment by tj** [comment]
ah yea that's just us setting up the make deps incorrectly, easy fix

**Comment by knownasilya** [comment]
Ok, I'll just remove `gulp` and keep the updates. I hope you update the Readme/makefile for building.

**Comment by jonathanong** [comment]
btw this isn't mergable

**Pull request closed without merging**
