### PR TITLE
listen signature with unix sockets support

### PR DESCRIPTION
**Pull request by magne4000**
See expressjs/express#3107

### CODE REVIEW

**Comment by dougwilson** [comment]
LGTM

**Comment by crandmck** [comment]
I think the wording needs to clarify that this listens on a Unix socket, e.g. the corresponding [Node doc](https://nodejs.org/api/http.html#http_server_listen_path_callback) says:

> Start a UNIX socket server listening for connections on the given path.

So, some wording similar to that...

Also, the existing [app.listen doc](http://expressjs.com/en/4x/api.html#app.listen) says "...This method is identical to Node’s http.Server.listen()" with link to the Node doc.

@dougwilson I assume the same is true for this signature?  If so, then we we should also link to https://nodejs.org/api/http.html#http_server_listen_path_callback in this section.

**Comment by dougwilson** [comment]
So I see the current wording is a copy and paste from the host + port section, simply changing out host and port to be path. @crandmck is really good with wording, so I think the ask here sounds good. Yes, this is the same as in http.Server. There is a link included that does point to the different docs, though the link's description is just http.Server.listen like the one below.

**Comment by crandmck** [comment]
>  There is a link included that does point to the different docs ..

Oops, quite right! How could I have missed that?  I think I got distracted by the big outage that left me unable to access GitHub on and off all morning :-(

**Comment by magne4000** [comment]
Updated

**Comment by hacksparrow** [comment]
Thanks @magne4000

**Pull request merged**
