### PR TITLE
documentation bug solved

### PR DESCRIPTION
**Pull request by Rizwan-Hasan**
**"res.locals.hello_world" =>  is not working and gives undefined**
Problem

**"res.app.locals.hello_world" => working fine.**
Working

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi, there are two locals locations. Your change is removing the docs for `res.locals`, which does exist. Just your example screenshots are expecting one to show up in the other.

**Comment by Rizwan-Hasan** [comment]
> Hi, there are two locals locations. Your change is removing the docs for `res.locals`, which does exist. Just your example screenshots are expecting one to show up in the other.

Wow, thanks for the quick response. Will you kindly lead me to how to do it then?

**Comment by dougwilson** [comment]
If you put a value in `app.locals` then you need to access though `app.locals`, but if instead you place the value in `res.locals`, then you would be able to retrieve thw value under `res.locals`.

**Comment by Rizwan-Hasan** [comment]
Understood, thanks for clearing up my confusion. 😊

**Comment by Rizwan-Hasan** [comment]
Is it ok to add this on the doc then?

**Comment by dougwilson** [comment]
It is already there; the docs are about how things work, not an endless enumeration of how things do not work. Are you saying there is a section in the docs that state values you set in `app.locals` are accessible from `res.locals`?

**Comment by Rizwan-Hasan** [comment]
The doc explains about creating an app.locals and accessing via req.app.locals but I tried to get it through res.locals thinking that it will inherit the object I've assigned into the app.locals. My mistake. But from this mistake, I get to know that it can be accessed through res.app.locals also which is not in the documentation. Now I ended up with the question of using it like this is standard or not.

**Comment by dougwilson** [comment]
It should be in there.

> The Express application object can be referred from the request object and the response object as req.app, and res.app, respectively.

**Comment by Rizwan-Hasan** [comment]
Finally, I've found it but in another section. But as long as it's standard and mentioned in the doc, I'm good to go with it. Thanks for taking your time and clearing things for me. 🥳🥳🥳

**Pull request closed without merging**
