### PR TITLE
Initial translated to Thai

### PR DESCRIPTION
**Pull request by iphayao**
Added Thai language directory for Thai translation and created required for Thai language in _includes/ directory.

### CODE REVIEW

**Comment by crandmck** [comment]
Thanks @iphayao !  I tried out your fork and it looks good.   

I have one request: Could you please add a link to the Thai home page to the English (main) front page, i.e.  in `_includes/footer/footer_en.html` on the line that says 
> Community translation available for: Slovak, Ukrainian, Uzbek and Turkish

add a link like `<a href="/th/">Thai</a>`

Otherwise, it won't be apparent that there is a Thai translation!

**Comment by iphayao** [comment]
Thank @crandmck for your reviewed, I did committed changed as your request to added Thai home page to English home page.

Please review my changed. Thank you

**Comment by crandmck** [comment]
Thanks!

**Comment by iphayao** [comment]
Thank!

**Pull request merged**
