### PR TITLE
asset optimizations

### PR DESCRIPTION
**Pull request by MehfoozurRehman**
so assets consume less bandwidth.

### CODE REVIEW

**Comment by crandmck** [comment]
Many of these assets are no longer used due to landing https://github.com/expressjs/expressjs.com/pull/1484.  But some (e.g. the Express logo) are still used.  

Using less bandwidth is good, so I'm inclined to land it, but can anyone speak to the specific details of the changes in this PR?

NOTE:  We also need a PR to remove all the company logos that used to be on the "Companies using Express" page removed in the above-mentioned PR.  Any takers?

**Comment by chrisdel101** [comment]
What do you need removed? I can do it. Do I need to wait until this PR  #1489 is merged before doing it?

**Comment by crandmck** [comment]
Some of the files modified in this PR are no longer used.  For example, I believe that the files in `images/companies` are no longer used anywhere since #1484 landed.

So modifying them doesn't serve any purpose.  How about removing them in this PR, then we can land it?  
Ideally, we would have some way of determining ALL the images that are no longer used, and just remove them, but that might be asking too much :-)

**Comment by MehfoozurRehman** [comment]
ok i am on it.

**Comment by chrisdel101** [comment]
Sorry, thought you were asking for a diff PR for a separate issue. If this is the case I can do that. But don't want to interfere with this current PR.

**Pull request closed without merging**
