### PR TITLE
Clarify next method.

### PR DESCRIPTION
**Pull request by davidyang**
Add some clarifying information about the next(err) method.

### CODE REVIEW

**Comment by crandmck** [comment]
Looks OK, but I would move the new section to the bottom of the existing section (and remove the added sub-header `## Handling errors`).

@hacksparrow What do you think?

**Comment by davidyang** [comment]
Hi @crandmck - have updated the pull request to reflect your comments.

**Comment by crandmck** [comment]
Thanks @davidyang.  Before merging, I'd just like to get input from @hacksparrow ...

**Comment by hacksparrow** [comment]
Good topic and good writeup. @davidyang can you remove the sub-heading? It breaks the context of the `next` object. Might sound obvious to us, but for those who are not familiar with Express, it can be very confusing.

Ready to merge after that.

**Comment by davidyang** [comment]
Hey @hacksparrow - removed the subheading - is that what you meant?

-# The `next(err)` method

**Comment by hacksparrow** [comment]
Yes @davidyang

**Pull request merged**
