### PR TITLE
fix: remove broken link for error handling 

### PR DESCRIPTION
**Pull request by aroyan**
Remove broken link in [Performance Best Practices Using Express in Production](https://expressjs.com/en/advanced/best-practice-performance.html) on Handle exceptions properly section, there is a link point to [Error Handling in Node.js](https://www.joyent.com/developers/node/design/errors) but the page is not found now and I can't find a replacement for this so I think this is better to be removed

### CODE REVIEW

**Comment by dougwilson** [comment]
Great find! Looks like Joyent moved their aite around and here is the new url: https://www.tritondatacenter.com/node-js/production/design/errors

**Comment by aroyan** [comment]
> Great find! Looks like Joyent moved their aite around and here is the new url: https://www.tritondatacenter.com/node-js/production/design/errors

Thank you, can't found them before. It's updated now

**Review by dhruvilxcode — APPROVED** [review]
👍🏻

**Review by dhruvilxcode — APPROVED** [review]
LGTM ✅

**Review by UlisesGascon — APPROVED** [review]

**Review by crandmck — APPROVED** [review]

**Pull request merged**
