### PR TITLE
feat - adjust in layout and theme

### PR DESCRIPTION
**Pull request by carlosstenzel**
Adjust in layout and theme

Before

https://github.com/expressjs/expressjs.com/assets/3890516/e123d4a2-294e-4998-9099-97c09bc592f4

After

https://github.com/expressjs/expressjs.com/assets/3890516/c600615f-05f7-46bb-a7fc-3a5d57d038eb

### CODE REVIEW

**Comment by crandmck** [comment]
Thanks @carlosstenzel ... this looks pretty good to me.

My only concern is that in dark mode the un-highlighted text does not have enough contrast with the background:
Screenshot 2024-05-26 at 11 35 37 AM

Could you please make it just a bit brighter/whiter?

I'd also like to get @chrisdel101's input.

**Comment by carlosstenzel** [comment]
Captura de Tela 2024-05-27 às 19 26 38

I changed the color to a lighter one

**Review by crandmck — APPROVED** [review]
The contrast looks much better now, thanks!

**Comment by chrisdel101** [comment]
Sorry for not getting to this yet. Will get to it this weekend.

**Comment by chrisdel101** [comment]
It's a bit tough to review the code with those formatting changes pushed into the diff. Is it possible to remove all that so only what you've actually changed is showing up? With 24 files to go through, it's a bit much to sort through as it is. 
If you could do that it'd make reviewing it much easier.
(I'm kind of a newer member of the review panel here, so apologies if this request is atypical)

**Comment by crandmck** [comment]
@carlosstenzel If you could please resolve the merge conflicts, and ideally take out the formatting changes as requested, we can probably land this.

**Comment by carlosstenzel** [comment]
@crandmck @chrisdel101 

Thanks guys, I'll be making the changes by the end of the week

**Comment by carlosstenzel** [comment]
@crandmck @chrisdel101

I created another PR without the formatting, please review again

https://github.com/expressjs/expressjs.com/pull/1528

**Comment by carlosstenzel** [comment]
Can we close this PR

**Pull request closed without merging**
