### PR TITLE
Embed a working example server on the "Hello World" tutorial

### PR DESCRIPTION
**Pull request by boucher**
I'd like to propose adding a runnable embedded Express server into the documentation, to make it easy for people to play around with Express and see how it works. I've implemented a fairly small set of changes to the existing "Hello World" tutorial to make this possible, which ends up looking like this:

screenshot 2017-06-20 11 44 29

Of course, I know that given this document needs to be translated, there are perhaps reasons to change the wording less, or perhaps people would prefer another approach or to discuss including on a different page.

This is powered by [RunKit](https://runkit.com) (which I helped create), which is creating a virtual server on demand behind the scenes. And if for whatever reason RunKit goes down, the example will fall back to just looking as it does now.

### CODE REVIEW

**Comment by crandmck** [comment]
The idea is fine in principle, and would probably be useful for readers learning Express.

My only reservation is using a commercial third-party service (runkit).  I don't think we want to imply that Express is endorsing it, even though it looks cool and useful.  If we did include this we would want a disclaimer to that effect.  Also, we might want to put it on a separate page so that it would be an optional path for Getting Started.

Thoughts @expressjs/express-tc ?

**Comment by hacksparrow** [comment]
I am not in favor of it. The Express API is simple enough, and the lesser external dependencies, the better.

**Comment by boucher** [comment]
I've put a version of the site online so you can play with it to get a better idea of how this works:
http://rossboucher.com/express/

@crandmck I'd be happy to add something in about not being an endorsement (or really, to rework this in whatever way you think makes the most sense for your users). 

I should also mention that our integration with [npmjs.com](https://npmjs.com) sends a number of users to the Express example hosted on [our site](https://npm.runkit.com/express), but I think it's a better experience to have the example closer to your own documentation.

@hacksparrow I do think the Express API is quite simple, especially once you've used it a bit. But I also think having a way to make changes and get immediate feedback would help some people figure it out more quickly.

And here's a (lowish quality, sorry) gif just for fun:
express3

**Comment by dougwilson** [comment]
So I am neutral about it, though it is very tempting because it looks like it would work very well. And yea, all npmjs.com listings have a link to RunKit currently, you can see this on the right-hand side of https://www.npmjs.com/package/express for example.

**Comment by crandmck** [comment]
Thanks @boucher for the example and your flexibility.  I think we would want some kind of disclaimer, but before word-smithing that, I'd like to see if we can come to a consensus on whether to add this at all.  So far we have one "nay" and one "neutral".  

I can't tell if @LinusU is in favor or neutral?  Anyone else care to weigh in, e.g. @blakeembrey ?

**Comment by LinusU** [comment]
> I can't tell if @LinusU is in favor or neutral?

Hehe, yeah sorry about that vague 👍 😄 

I agree with everything you said in that message, I think it's a really nice feature but we should make clear that it's from a third party that we are not endorsing...

Super nice example though @boucher, great work!

**Comment by jdalton** [comment]
If you all are looking for another example integration, I added runkit to [Lodash's documentation](https://lodash.com/docs/4.17.4) about a year ago. The Lodash site runs offline and toggles the repl off when in offline mode and other such things. I went all out with resource hints and all that jazz. Runkit has a preview of code style themes I still need to look into now too. I dig them for sure.

**Comment by dougwilson** [comment]
Nice. I mean, if it does cause a technical issue, we can always remove it.

**Comment by crandmck** [comment]
OK, so Linus is for it, and possibly Doug is coming around (?).  I'm leaning toward accepting this PR, too.  It's a neat capability.

But I do think we should add some disclaimer text like:

> RunKit provides an interactive JavaScript playground connected to a complete Node environment that runs in your web browser.  RunKit is a third-party service that is not affiliated with Express and the Express team is not responsible for any bugs or issues with it.  

We could also include something a bit more forceful like:

"It is included here for the convenience of people learning Express, and does not constitute an endorsement by the Express project."

Thoughts?

**Comment by jdalton** [comment]
> "It is included here for the convenience of people learning Express, and does not constitute an endorsement by the Express project."
>
>Thoughts?

From an outsider it seems overly formal. In my experience with runkit in Lodash, which is the most directly depended upon package in the npm ecosystem with 203K+ active users visiting the site a month, I've not had any push back or support burden related to the doc repl.

**Comment by crandmck** [comment]
> From an outsider it seems overly formal.

Yeah, that's probably due to my background as a tech writer working on commercial projects for over 25 years (yikes!).  For an OS project, I agree it's probably overkill.  I think the first blurb is probably sufficient, but I'd like to see what others think.

**Comment by dougwilson** [comment]
I say let's go for it, given further evidence that this is a product used around in multiple places. As for the disclaimer, I do agree that it is a bit strong, though I absolutely know where @crandmck is coming from :) Being that the site is not actually run by a company, though, I'm not sure that most of the disclaimer is really necessary. I think that it being on every package screen in npm without an endorsement disclaimer already may make people who would need such a disclaimer already think that packages are "endorsing it".

Perhaps I can see a use of adding the support comment, though that just adds wording that may confuse people, so we could always add it if it does become an issue.

Anyway, just my thoughts :)

**Comment by crandmck** [comment]
OK, sounds good.  I still think it makes sense just to clarify that RunKit is entirely separate from 
 Express.  Perhaps that's obvious to us, but for a random person it might not be. 

So how about just adding:

> RunKit provides an interactive JavaScript playground connected to a complete Node environment that runs in your web browser. RunKit is a third-party service not affiliated with the Express project.

That's pretty minimal and just a statement of fact to eliminate any possible confusion.

**Comment by boucher** [comment]
@crandmck added

**Comment by crandmck** [comment]
LGTM. I might tweak the formatting at some point, but good enough for now.

**Comment by boucher** [comment]
Thanks everyone! Let me know if you run into any trouble or have any suggestions for ways we could make this better for you. 

(Quick question: should I be doing something about getting the changed language translated into the other supported languages?)

**Comment by crandmck** [comment]
> should I be doing something about getting the changed language translated into the other supported languages

Sorry for the delay, I've been on vacation--we rely on the community to update translations, so it's up to speakers of each language (German, Spanish, etc.) to open PRs for each language.

**Pull request merged**
