### PR TITLE
Update hello-world.md

### PR DESCRIPTION
**Pull request by cagataycali**
Looks better :+1:

### CODE REVIEW

**Comment by crandmck** [comment]
I think this is OK, but since we don't use arrow functions anywhere else in the docs, I wonder if this could potentially cause some confusion, for example for someone not familiar with them?

Do you have an opinion or preference @dougwilson ?

**Comment by dougwilson** [comment]
I'm not too concerned with thr arrow functions, but I am concerned with the line

    const app = require('express')()

The immediate invoke has in the past caused a lot of users confusion, from (1) not realizing there was a () on the end and trying to run code without it and (2) get confused as soon as they tried to use express.static or express.Router

I think if that line is back to two separate lines the arrow function changes itself is fine.

**Comment by cagataycali** [comment]
I agree with you guys, seperated back in two lines.

**Comment by crandmck** [comment]
Great, works for me... Thanks @cagataycali

**Pull request merged**
