### PR TITLE
init file structure for Chinese lang and make some translations

### PR DESCRIPTION
**Pull request by wangsai**

### CODE REVIEW

**Comment by crandmck** [comment]
@hacksparrow Could you take a look at this and merge if it looks OK?

**Comment by hacksparrow** [comment]
Yes, I will be reviewing it and merging it if all looks good.

**Comment by hacksparrow** [comment]
Looking good. Xie xie, @wangsai!

**Comment by wangsai** [comment]
Bu ke qi  :smile: 

I'll translate all the docs as soon as possible.

**Comment by hacksparrow** [comment]
👍

**Pull request merged**
