### PR TITLE
feat: improve admonitions notes

### PR DESCRIPTION
**Pull request by bjohansebas**
Colors have been changed because their meanings were not visually distinguishable, making the documentation difficult to read. Additionally, in dark mode, the colors were not displayed correctly.

Notice:
image
image
image
image
Note:
image
image
image
image
Warn:
image
image
image
image

### CODE REVIEW

**Comment by crandmck** [comment]
Thanks @bjohansebas in general, this looks good.  

These things are typically called "admonitions" not "asides".  Could you change the directory to that just for sake of conforming to industry standards.

Also, this is a fairly sweeping change and I didn't have time to review it in depth yet.  Maybe @chrisdel101 or @inigomarquinez  can help on that front.

**Comment by chrisdel101** [comment]
The code changes look fine to me. I didn't go through every single page in preview but the ones I did see look pretty nice!
@bjohansebas If you want to make those directory changes as requested.

**Comment by bjohansebas** [comment]
@crandmck @chrisdel101 thanks for the recommendation; the directory name change has been made.

**Comment by crandmck** [comment]
I'll land this, but would like to understand why the `check-translation` test is failing.

**Comment by bjohansebas** [comment]
@crandmck It's an issue we've been referencing in #1553. Probably @IamLizu will have the solution and explanation once it's resolved.

**Review by carlosstenzel — APPROVED** [review]

**Pull request merged**
