### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by Felichz**
Fixes to the issue [https://github.com/expressjs/expressjs.com/issues/1168](https://github.com/expressjs/expressjs.com/issues/1168)

### CODE REVIEW

**Review by Felichz — COMMENTED** [review]
Updated "**[Production best practices: performance and reliability](https://expressjs.com/en/advanced/best-practice-performance.html)**" article in his [Spanish version](https://expressjs.com/es/advanced/best-practice-performance.html) to match with the current English version

**Comment by lkamazaezuzemedium** [comment]
$ add

**Review by crandmck — APPROVED** [review]
This looks fine to me.

**Comment by crandmck** [comment]
thanks for the contribution!

**Pull request merged**
