### PR TITLE
change Jade to Pug in multiple language guides

### LINKED ISSUE #618: Update translated docs for Jade -> Pug
Need to update all translated docs with same changes as in #616.

### PR DESCRIPTION
**Pull request by JonathanPrince**
change Jade to Pug in guides for remaining languages, resolves #618

### CODE REVIEW

**Comment by hacksparrow** [comment]
Thanks for the PR @JonathanPrince. However, we are not supporting Pug till it comes out of beta. Even then, there might be some changes in the default or no-default view engine. Just letting you know that this PR is going to sit here for while.

**Comment by JonathanPrince** [comment]
Thanks for letting me know @hacksparrow. Just to avoid any confusion, similar changes are already merged for english #616 and german #715, let me know if/when I can help with anything.

**Comment by hacksparrow** [comment]
I see! @crandmck should have the context of the merges. Let's wait for him to handle this as well.

**Comment by crandmck** [comment]
Sorry, been slammed with other work...

Looking into this, I may have been too hasty in updating "Jade" to "Pug" everywhere... 
I somehow got the impression that the generator had been updated, but I see from https://github.com/expressjs/generator/pull/117 that this hasn't actually happened yet.
I probably assumed that when the PR with the changes was merged, they were also released to npm--which obviously is a dumb assumption :-(

Which means perhaps I shouldn't have merged those other PRs (#616 and #715 ) so quickly.  
_sigh_  If we can avoid backing those out, that would be ideal, but we do need to make sure that what we have is correct.

Until the generator is updated, it makes it difficult to document clearly--since people should start using Pug to make sure they're getting the "latest and greatest" version of Jade (Pug), but they would have to make a bunch of manual changes if they're using the generator.

I think most of the changes in http://expressjs.com/en/guide/using-template-engines.html are OK, even if the generator hasn't been updated.  EXCEPT, this is not actually true:

> The Express application generator uses Pug as its default

Anyway, let's wait to merge this PR open until generator 4.14 is released.  
I'll fix the above line in the English docs.  @hacksparrow If you see anything else that needs to change, please let me know.

**Review by sandizapar — APPROVED** [review]

**Review by sandizapar — APPROVED** [review]

**Comment by crandmck** [comment]
This should have been landed a long time ago, since https://github.com/expressjs/generator/pull/117 has been in for over a year.  

Sorry for the delay.

**Pull request merged**
