### PR TITLE
Update Companies Using Express

### PR DESCRIPTION
**Pull request by RoyalRajdeep**
Hey There !

I have made few updates for the "Companies using Express"  Page.
The list of companies using expressjs can be found [ here](http://stackshare.io/expressjs/in-stacks).

Following things are updated there.
 A New Directory is created for this page. 
4 New Logos added. (As they are StackShare Verified Users of Express).
UBER was re-branded in last Feb but still here there was old logo of UBER.
Some Logos were not in transparent PNG format so I made them in transparent background so all the logos look consistent.
More spacing between logos added.

*Please ignore GemFile.lock Changes in merge.

### CODE REVIEW

**Comment by bajtos** [comment]
@crandmck @hacksparrow PTAL

**Comment by crandmck** [comment]
Thanks!

**Comment by RoyalRajdeep** [comment]
Welcome @crandmck.
Can I go for the rebuild of whole website with improved UI ?
Also Can you confirm me that light black coloured "ex" in Helvetica Font is the official logo of Express Js ?

**Comment by crandmck** [comment]
> Can I go for the rebuild of whole website with improved UI ?

Can you be more specific about what you're proposing?  

The proper way to do this would be to open a new issue with your specific proposal and why you think it's needed.

> Also Can you confirm me that light black coloured "ex" in Helvetica Font is the official logo of Express Js ?

Well, the "logo" is really just the word "Express", styled as it is on the home page.  The little "ex" image is just what we've used for the favicon--I wouldn't call it "official".

**Comment by RoyalRajdeep** [comment]
I am using Express from last one and half year. Each Library and Framework I use, Have their own Branding, Iconic Logos, and Color theme, But Express is still not having any specific color theme, Iconic brand Logo. We are just having a simple b/w color themed website and a very simple logo type.

If Express Js community have the same thought , then I go ahead for this part to 
1. Suggest a new color theme for all Express Js related stuff. (Like NodeJS has Green+Grey, and they use the same Color Combination on all their stuff, Angular has Pink+White.)
2. Design a new logo for express, based on our community suggestions.

For the Website Part I will made a proposal soon.

**Pull request merged**
