### PR TITLE
New example app: StudyNotes

### PR DESCRIPTION
**Pull request by feross**
Submitting my app ([StudyNotes](http://www.apstudynotes.org)) via pull request as requested by @jonathanong in https://github.com/visionmedia/expressjs.com/issues/89#issuecomment-30272706.

studynotes 2x

### CODE REVIEW

**Comment by jonathanong** [comment]
you gotta edit the jade only: https://github.com/visionmedia/expressjs.com#contributing

**Comment by feross** [comment]
Right, sorry about that. Just fixed it!

**Comment by jonathanong** [comment]
LGTM. anyone?

did we figure out the dimensions thing?

**Comment by feross** [comment]
For the dimensions, I sized my window to match the others and used Safari with all toolbars hidden. Then I compressed it with Photoshop using "Save for web" and saved a half-size (non-retina) version.

The image looks like it fits right in with the rest.

**Pull request merged**
