### PR TITLE
Add notes about automatic HEAD

### PR DESCRIPTION
**Pull request by dougwilson**
Proposed notices to add regarding the "automatic HEAD" feature of Express routing for #748

### CODE REVIEW

**Comment by syrnick** [comment]
Looks great! Can `HEAD` be a link to https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4 ?

**Comment by dougwilson** [comment]
Since RFC 2616 is obsolete and has been replaced, I would not link to that, personally.

**Comment by syrnick** [comment]
sounds good

**Review by crandmck — APPROVED** [review]
LGTM, thanks!

**Comment by renatoargh** [comment]
does any one know if there is a way to turn off this automatic head feature?

**Comment by ryhinchey** [comment]
> does any one know if there is a way to turn off this automatic head feature?

@renatoargh There isn't a configuration to let you have get routes not respond to head requests.  That said, `get` routes should only respond to `head` requests if `app.head` was not called before `app.get`.  Here are the docs:

https://expressjs.com/en/api.html#app.METHOD

```
The app.get() function is automatically called for the HTTP HEAD method in addition to the GET method if app.head() was not called for the path before app.get().
```

Hope this is helpful!

**Pull request merged**
