### PR TITLE
docs: update broken link for socket.io docs

### PR DESCRIPTION
**Pull request by aroyan**
Update to v4 of socket.io docs

### CODE REVIEW

**Comment by dougwilson** [comment]
Awesome, thanks! Would you be willing to update the other references to this same link in the website?

**Comment by aroyan** [comment]
> Awesome, thanks! Would you be willing to update the other references to this same link in the website?

I would love to, but how to find that?

**Comment by aroyan** [comment]
> Awesome, thanks! Would you be willing to update the other references to this same link in the website?

Sure, already updated it

**Review by srkds — APPROVED** [review]
LGTM 👍

**Review by UlisesGascon — APPROVED** [review]
LGTM! 👾

**Review by UlisesGascon — APPROVED** [review]
LGTM! 👾

**Pull request merged**
