### PR TITLE
Added info to disable file upload (bodyParser)

### PR DESCRIPTION
**Pull request by madarche**

### CODE REVIEW

**Comment by tj** [comment]
cool, we should maybe link to that message I added in the mailing list so there's some context

**Comment by madarche** [comment]
Is it this link https://groups.google.com/d/msg/express-js/iP2VyhkypHo/5AXQiYN3RPcJ ?

**Comment by tj** [comment]
yup!

**Comment by madarche** [comment]
Ready to be merged

**Comment by tj** [comment]
great thanks!

**Pull request merged**
