### PR TITLE
Add api-error-handler docs

### PR DESCRIPTION
**Pull request by mifi**
and example code

I was digging for an hour or so trying to find such a middleware, only to realise that it was provided by express all along!

### CODE REVIEW

**Review by dougwilson — CHANGES_REQUESTED** [review]
There are many modules that do this and similar. The guide here is around how to write your own rather than linking to other middlewares. It should likely be added to this page: https://expressjs.com/en/resources/middleware.html

**Comment by dougwilson** [comment]
Oh, I looked at the history and it was removed because the author no longer maintains it. I will archive the repo in the org. I don't have access to the npm module itself, so nothing I can do to mark it there besides the repo.

**Comment by mifi** [comment]
Ok, thanks for cleaning up. I couldn't find any other npm package that does this, in a simple clean way.

I created a fork [error-handler-json](https://github.com/mifi/error-handler-json) that I upgraded to latest deps and intend to maintain. Any chance you could link to that from the original archived project's readme, so that any lost souls can find an alternative?

Also, do you think I can submit a PR to add this new fork to https://github.com/expressjs/expressjs.com/blob/gh-pages/en/resources/middleware.md

And possibly a line in https://github.com/mifi/expressjs.com/blob/gh-pages/en/guide/error-handling.md under "The default error handler" saying something like "If you want to return errors as JSON instead of HTML, you may look into this module"?

Thanks!

**Comment by dougwilson** [comment]
Ok, that's great!

> I created a fork [error-handler-json](https://github.com/mifi/error-handler-json) that I upgraded to latest deps and intend to maintain. Any chance you could link to that from the original archived project's readme, so that any lost souls can find an alternative?

I'll get the readme edited on the repo here.

> Also, do you think I can submit a PR to add this new fork to https://github.com/expressjs/expressjs.com/blob/gh-pages/en/resources/middleware.md

Feel free to send over a PR adding it to the middleware page ❤️ 

> And possibly a line in https://github.com/mifi/expressjs.com/blob/gh-pages/en/guide/error-handling.md under "The default error handler" saying something like "If you want to return errors as JSON instead of HTML, you may look into this module"?

It's going to be a bit beyond the guide and from experience is going to cause some issues with folks who want to start adding on there. Ideally it should be a guide for how to use Express.js error handling, such that they could _create_ such a module. If anything pointing elsewhere, it could point to the middlewares page so that would also keep a single place where the middleware are listed.

**Pull request closed without merging**
