### PR TITLE
Update hello-world.md

### PR DESCRIPTION
**Pull request by hyeonjae**
update old sample code

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @hyeonjae, it looks like there are two things here:

1. updates to the example to make it use arrow functions
2. adding a script from runkit

So I am not opposed to number 1, even though I think it is unnecessary.  But Number 2 is something I think we should avoid.  If we are going to do code highlighting (which is my assumption about what this does) I really dont want to do it with a third party script.

**Comment by crandmck** [comment]
@hyeonjae removed the Runkit stuff, so what's left is just changing `var` to `const` and using arrow functions.  In some ways, I think using arrow functions may obfuscate the sample code, even though it's more "modern" JS.  Can we safely assume that all readers will know arrow functions?
@wesleytodd @dougwilson Do you want to weigh in?

**Comment by wesleytodd** [comment]
>  Can we safely assume that all readers will know arrow functions?

I think we can.  If nothing else it will not be a put off to the more "modern" folks out there.  My concern is that with our delay in 5.0 it might increase the concern about the project momentum being low if we also are not using modern and common syntax.  So in this case I think it is good to update the docs.

**Comment by dougwilson** [comment]
I'm not opposed to it. This section is not even express version-specific.

**Pull request merged**
