### PR TITLE
add cozy to the applications section

### PR DESCRIPTION
**Pull request by frankrousseau**
Follow-up of the #54 issue.

Thank you Jonathan.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Please remove the built html file and just leave the jade and image changes.

**Comment by frankrousseau** [comment]
Sorry for that. Now my commit should be clean. Tell if I need to change anything else.

**Comment by defunctzombie** [comment]
LGTM @jonathanong @visionmedia any objections?

**Comment by tj** [comment]
LGTM

**Comment by tj** [comment]
would be nice if we documented the dimensions for people haha that's the main reason I haven't added too many, just a PITA to get that size correct

**Comment by defunctzombie** [comment]
@visionmedia what are the dimensions? I can add it to the requirements section.

**Comment by tj** [comment]
no clue :D

**Comment by defunctzombie** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by tj** [comment]
¯_(ツ)_/¯

**Comment by frankrousseau** [comment]
Hi all, thank you for the merge! By the way, if you have 5 minutes, have a look at Cozy, it encourages people to build personal web apps with Express. What is really good is that apps can collaborate together to provide new usages (communication is based on Axon).

**Comment by jonathanong** [comment]
> Please remove the built html file and just leave the jade and image changes.

should we do this from now on? i find it difficult because i have to rebuild everything to see any changes (unless i'm doing it wrong).

**Comment by defunctzombie** [comment]
@jonathanong I think change commits should only have the changes they introduced and we make build commits separately. I think that will be less error prone cause it is much easier to miss some build error in the diff noise.

**Comment by jonathanong** [comment]
okay sounds fine to me. just a PITA. we should add that to the readme though.

**Pull request merged**
