### PR TITLE
Update router-route.md

### PR DESCRIPTION
**Pull request by ifraixedes**
Although with the comment into `.all(function (req, res, next)` is clear that it is a middleware and `next` must be called, in other examples always appear the `next` call, so I think that it is more consistent with the rest of the docs.

### CODE REVIEW

**Comment by crandmck** [comment]
@dougwilson - Could you please review this addition.  (@hacksparrow is out for essentially rest of the month).

**Comment by dougwilson** [comment]
Just the `next()` is really necessary; the other part of yelling at the doc readers in caps and printing to console is not necessary.

**Comment by ifraixedes** [comment]
I've updated the PR, removing `console.log`

**Comment by dougwilson** [comment]
LGTM

**Comment by crandmck** [comment]
Thanks @dougwilson and @ifraixedes.

**Pull request merged**
