### PR TITLE
Fix for issue #116 (replaced build files).

### PR DESCRIPTION
**Pull request by ghost**
Okay, put the build files back in and squashed with my changes, let's hope I did it right this time.

Apologies for all the branches and pull requests now :(

### CODE REVIEW

**Comment by defunctzombie** [comment]
I still see `api.html` as being removed in your commit.

No apologies needed! Some of the stuff can be confusing :)

**Comment by ghost** [comment]
Oh man, can't believe I missed one. Prepare yourself for yet another branch lol.

**Comment by defunctzombie** [comment]
@austindavies btw, you don't have to branch. You can just fix the change in your branch and force push.

**Comment by ghost** [comment]
Okay I think that did it.

Thanks for the tip!

**Comment by defunctzombie** [comment]
@austindavies the reason we do it like this is to allow for manual review of the built files ourselves before pushing built changes. It also makes the commits that actually fix things less noisy.

**Comment by ghost** [comment]
@defunctzombie Makes perfect sense, thanks for being patient with me.

**Comment by ghost** [comment]
@defunctzombie Something isn't right with the homepage. It looks completely broken to me.

**Comment by defunctzombie** [comment]
@austindavies the homepage should not have changed yet since it has not been built.

**Comment by tj** [comment]
i think this buggered up the api page a bit, there's an hr at the top now, and the padding seems weird now, if you have a thin-ish page the menu overlaps now

**Comment by ghost** [comment]
@visionmedia Just noticed, and you're right, it's the reason I chose to hide the menu on smaller displays. I'll fix the padding so content adapts to the menu so they never overlap. I'll remove the hr too, not sure why I kept it in the first place, looks neater without.

**Comment by tj** [comment]
rad thanks man!

**Comment by tj** [comment]
oh yeah you're right, home page is broken haha.. we should stop accepting CSS patches after this, too much to review

**Comment by defunctzombie** [comment]
web dev is hard :'(

**Pull request merged**
