### PR TITLE
Update express.json.md

### PR DESCRIPTION
**Pull request by toymachiner62**

### CODE REVIEW

**Comment by toymachiner62** [comment]
Fixes #1011

**Review by dougwilson — CHANGES_REQUESTED** [review]
The wording that was changed at the top here is the same wording used for all the build-in middlewares: express.json, express.urlencoded, and express.static. They should all be using the same wording / linkage so they are not all slightly different when they should have the same underlying meaning.

I'm not sure if this is the right wording here, but at the very least, this should keep the wording for these three pieces in sync in the PR.

**Comment by toymachiner62** [comment]
While i don't necessarily agree with the current language (mainly since `express.json` is not based on `body-parser`, but rather IS `body-parser`, I respect your wishes and changed it back.

**Comment by wesleytodd** [comment]
I think you both are agreeing with subtle variations.  I think @dougwilson intended to say that if you want to improve the wording (as you say, it IS `body-parser`, which IMO is a good change), then you should do it in all three places `.json`, `.urlencoded` and `.static`.  I think a reasonable PR would be to change all three in one go.

**Comment by dougwilson** [comment]
Exactly.

**Pull request closed without merging**
