### PR TITLE
feat: update website to support Ruby 3.3.5 compatibility (from 3.1.1)

### PR DESCRIPTION
**Pull request by Shantanugupta43**
I made this website compatible with the latest Ruby version 3.3.5 as the package was too old and repository config was crashing locally when ```bundle install``` was run due to the latest version.

<h2>Error</h2>

```
PS C:\Users\gupta\Downloads\expresswebsite\expressjs.com> bundle install
Your Ruby version is 3.3.5, but your Gemfile specified 3.1.1

```
<h2> Latest Ruby release </h2>

image

<h2> After updating to latest version </h2>

image

image

### CODE REVIEW

**Comment by bjohansebas** [comment]
I get the following error when using `make serve` with the new changes
```
\033[1;34mStarting expressjs.com at http://localhost:4000\033[0m
docker run -p 4000:4000 -p 35729:35729 -v /home/bjohansebas/Dev/expressjs.com-fork:/usr/src/app expressjs.com
Resolving dependencies...
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:603:in `materialize': Could not find github-pages-231, jekyll-3.9.5, jekyll-commonmark-ghpages-0.4.0, i18n-1.14.5, rexml-3.3.2, racc-1.8.0, faraday-2.10.0, concurrent-ruby-1.3.3, activesupport-7.1.3.4, strscan-3.1.0, faraday-net_http-3.1.1, minitest-5.24.1, uri-0.13.0 in locally installed gems (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:193:in `specs'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:260:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:18:in `setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:164:in `setup'
	from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:25:in `load'
	from /usr/local/bundle/bin/jekyll:25:in `<main>'
```

**Comment by Shantanugupta43** [comment]
> I get the following error when using `make serve` with the new changes
> 
> ```
> \033[1;34mStarting expressjs.com at http://localhost:4000\033[0m
> docker run -p 4000:4000 -p 35729:35729 -v /home/bjohansebas/Dev/expressjs.com-fork:/usr/src/app expressjs.com
> Resolving dependencies...
> /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:603:in `materialize': Could not find github-pages-231, jekyll-3.9.5, jekyll-commonmark-ghpages-0.4.0, i18n-1.14.5, rexml-3.3.2, racc-1.8.0, faraday-2.10.0, concurrent-ruby-1.3.3, activesupport-7.1.3.4, strscan-3.1.0, faraday-net_http-3.1.1, minitest-5.24.1, uri-0.13.0 in locally installed gems (Bundler::GemNotFound)
> 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:193:in `specs'
> 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:260:in `specs_for'
> 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:18:in `setup'
> 	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:164:in `setup'
> 	from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
> 	from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
> 	from /usr/local/bundle/bin/jekyll:25:in `load'
> 	from /usr/local/bundle/bin/jekyll:25:in `<main>'
> ```

That's interesting. I got a different error but it seems to have fixed the docker issue. Can you give it a check?

Here is what I got first

image

Then the code suggested to use ``bundle exec jekyll serve`` which i modified in makefile and then it started to work.

image

Webpage is visible

image

**Comment by Shantanugupta43** [comment]
@bjohansebas Have you got latest version of ruby installed which is 3.3.5? It may be a result of what you are getting if your ruby version is 3.1.1

**Comment by bjohansebas** [comment]
@Shantanugupta43 My Ruby version is 3.2.5 locally, but in Docker it should install 3.3.5, and it shouldn't conflict with the one I have installed locally. I also ran `docker system prune -a` to delete all my containers, and it still doesn't work.

```
\033[1;34mStarting expressjs.com at http://localhost:4000\033[0m
docker run -p 4000:4000 -p 35729:35729 -v /home/bjohansebas/Dev/expressjs.com-fork:/usr/src/app expressjs.com bundle exec jekyll serve --host 0.0.0.0
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:603:in `materialize': Could not find github-pages-231, jekyll-3.9.5, jekyll-commonmark-ghpages-0.4.0, i18n-1.14.5, rexml-3.3.2, racc-1.8.0, faraday-2.10.0, concurrent-ruby-1.3.3, activesupport-7.1.3.4, strscan-3.1.0, faraday-net_http-3.1.1, minitest-5.24.1, uri-0.13.0 in locally installed gems (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:193:in `specs'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/definition.rb:260:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/runtime.rb:18:in `setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler.rb:164:in `setup'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/setup.rb:32:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:159:in `with_level'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:111:in `silence'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/setup.rb:32:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
make: *** [Makefile:19: serve] Error 1
```

**Comment by Shantanugupta43** [comment]
@bjohansebas It seems like your gems are not installing correctly. Can you try using the ``gem list`` command and send a screenshot of what comes up?

**Comment by bjohansebas** [comment]
I find it difficult to use the command you mentioned because I use Docker, and I can't access the container since it fails to start and I can never access it:
```
Error response from daemon: container 6963d14ae8d27b7774a3ccfa1474c03316e7f8dcd5fd2904137aad76e795c883 is not running
```

**Comment by Shantanugupta43** [comment]
@bjohansebas Gemfile.lock file is used by Bundler to ensure that all dependencies are resolved to the exact versions specified. If this file is deleted right after installing the gems, Bundler might not have the correct information to properly set up the environment or verify the installed gems, which can lead to issues if the Docker container relies on it.

So i decided to retain it. Let me know if it works.

Also use ``docker build --no-cache -t expressjs.com .`` to build the image again then use ``make serve``

**Comment by bjohansebas** [comment]
It still doesn't work, maybe the problem is related to the version of GitHub Pages? https://pages.github.com/versions/

**Comment by Shantanugupta43** [comment]
> It still doesn't work, maybe the problem is related to the version of GitHub Pages? https://pages.github.com/versions/

It cannot be that or else it wont work on my machine. Even though generation of Gemfile.lock is automatic, I committed the lockfile for you to check if it aligns with your dependency. The issue is definitely around dependencies. 


image

Can you try to run ``docker exec -it <container_id> bash`` to enter the container and manually run ``bundle check`` or ``bundle install`` to see if any gems are missing.

For example

image

**Comment by bjohansebas** [comment]
Yeah, now it works.

**Review by bjohansebas — APPROVED** [review]

**Comment by Shantanugupta43** [comment]
Hi, I just wanted to check in on this PR and see if there are any updates or feedback that would help move it forward. Please let me know if any additional changes are required.

**Review by UlisesGascon — COMMENTED** [review]
Seems good! Thanks for the work on this @Shantanugupta43!

Do we need to include the `Gemfile.lock`? Even if we have the `Gemfile` already. I am not very familiar with Ruby at all.

**Comment by Shantanugupta43** [comment]
> Seems good! Thanks for the work on this @Shantanugupta43!
> 
> Do we need to include the `Gemfile.lock`? Even if we have the `Gemfile` already. I am not very familiar with Ruby at all.

Yes @UlisesGascon I would suggest to include Gemfile.lock file as without the lock file it was causing some dependencies to not be found while only installing from Gemfile in docker.

That's why you may notice the Dockerfile contains installation of Gems as well as it copies from Gemfile.lock to ensure consistancy in the new change.

**Comment by Shantanugupta43** [comment]
@UlisesGascon Also it was an interesting issue as I used ```bundle install``` in my cmd and then tried ```make serve``` the Gemfiles aligned accordingly. It also worked when I tried using the make commands alone without the Gemfile.lock file. But looks like there were some issues when @bjohansebas tried using Docker to make build and serve the file which seemed to be resolved when I included the Gemfile.lock and changed the dockerfile to copy the lockfile.

**Comment by bjohansebas** [comment]
I'm going to launch this.

**Comment by bjohansebas** [comment]
@Shantanugupta43 thanks

**Comment by Shantanugupta43** [comment]
> @Shantanugupta43 thanks

No worries! 👍

**Comment by bjohansebas** [comment]
@expressjs/docs-wg Please run `make build` again so that Docker works locally

**Comment by jonchurch** [comment]
The reason we dont include gemfile lock here is that we are attempting to emulate gh-pages, which will ignore the lockfile so far as I understand. 

The docker file shouldnt even require installing jekyll, as the gh-pages gem will instead install the version which gh-pages will use as well as all dependencies available in gh-pages builds. 

We may stabilize the local dev and deploy preview experience via the lockfile, but at the cost of no longer replicating the deploy environment we are targeting.

**Pull request merged**
