### PR TITLE
Add Visitors Book project

### PR DESCRIPTION
**Pull request by anton-marchenko**
Add information about Visitors Book (open-source project that uses Express).

[Proof link](https://github.com/anton-marchenko/am.visitors-book/blob/02aacc1cfb58e87cb82af9ee4a4ffe80b0b0c4f8/package.json#L18) about Express usage.

This project was written by TDD methodology (and has 100% test coverage). Because of this, the project is important for community as study material.

### CODE REVIEW

**Comment by anton-marchenko** [comment]
Waiting for https://github.com/expressjs/expressjs.com/pull/1094

**Comment by wesleytodd** [comment]
I am hoping we can move most of this content off of the website sometime and into something more like an "awesome list".  It is tough to maintain the content we have now, and I just don't want to make the situation worse.  It is nothing against this example, but I am in general turning this kind of changes away.

**Comment by anton-marchenko** [comment]
> I am hoping we can move most of this content off of the website sometime and into something more like an "awesome list". It is tough to maintain the content we have now, and I just don't want to make the situation worse. It is nothing against this example, but I am in general turning this kind of changes away.

But what about this description:
image

We need to delete this description in this case.

**Comment by wesleytodd** [comment]
Sorry!  I totally understand how that is miss-leading.  It is not our intention, but much of the content on the website was written many years ago.  Thanks for opening that pr!

**Pull request closed without merging**
