### PR TITLE
Update applications.md

### PR DESCRIPTION
**Pull request by freedomson**
Hello, hope you pubslish my work. Thanks for the good job, express is just great. Best regards from Portugal, Philip Almeida

### CODE REVIEW

**Comment by freedomson** [comment]
gugamarket

I just uploaded the screenshot.

**Comment by hacksparrow** [comment]
@freedomson we can merge this if can you fix the invalid certificate problem.

screen shot 2015-10-12 at 10 19 14 pm

**Comment by freedomson** [comment]
Just removed the https links and add regular http url.

**Comment by freedomson** [comment]
The image is missing. Just made a pull request for the png file in https://github.com/strongloop/expressjs.com/pull/465

**Pull request merged**
