### PR TITLE
Indicate that etag option default is `weak`

### PR DESCRIPTION
**Pull request by madarche**
cf. [code of application.js](https://github.com/strongloop/express/blob/master/lib/application.js#L74)

### CODE REVIEW

**Comment by dougwilson** [comment]
Looks good :)

**Comment by madarche** [comment]
@hacksparrow @dougwilson, please, how should such modifications be ported to the `5.x` branch? Is it "your" job, as maintainers, to merge it? Or should any contributor to expressjs.com take care of the `5.x` branch too?

Cheers

**Comment by hacksparrow** [comment]
@madarche it is open for everyone to open PRs to this repo. Feel free to do so, if you have anything on your mind.

**Comment by madarche** [comment]
@hacksparrow I mean: What is the recommended workflow that has been devised to make sure that all fixes/features contributed in the `4.x` branch actually end up in the `5.x` branch too? Thanks

**Comment by hacksparrow** [comment]
The last commit on `5.x` was on 24th July. We'll have to review the commits / PRs to `4.x` in the meantime, and merge accordingly.

**Comment by madarche** [comment]
OK. Thank you!

**Comment by hacksparrow** [comment]
@madarche are you planning on doing that, btw? 5.x release is quite near now, we need to start merging.

**Comment by madarche** [comment]
@hacksparrow I would be glad to help on that. But with limited time I'm focusing on documenting other things (some more PRs to come) rather than working on this 5.x merge. So to conclude: I was asking 1st to be sure that my work would not be lost when 5 is released, and 2nd so my work fits in well with the global "publication workflow" (because another option could have been that contributors should provide both a PR for "stable" branch and a PR for "next" branch).

**Comment by hacksparrow** [comment]
@madarche great, looking forward to the PRs. The PR-to-both-branches approach could _potentially_ cause conflicts and everyone might not be keen on doing two PRs. Since we have to review everything anyway, a PR to `gh-pages` should serve the purpose.

**Pull request merged**
