### PR TITLE
Add express-slick-css to middleware.md

### PR DESCRIPTION
**Pull request by ameerthehacker**
I have developed a middleware called [https://github.com/ameerthehacker/express-slick-css](express-slick-css). It removes all the unused CSS rules before sending the response as a page. It is relatively new yet I believe this is one way I can take this to a huge audience of expressjs If you people feel my middleware is up to it!

### CODE REVIEW

**Comment by crandmck** [comment]
I have no specific objections to this addition, but see discussion in #966. 
My main concern is that we can't possibly list _all_ the middleware that exists, so where do we draw the line?

@wesleytodd @dougwilson PTAL

**Comment by dougwilson** [comment]
Without there being a formal definition of what should be in there and what should not, I have no objection to adding it in.

**Comment by ameerthehacker** [comment]
Thanks @dougwilson

**Comment by ameerthehacker** [comment]
@crandmck any updates on this PR?

**Comment by wesleytodd** [comment]
I would like to think on this for a bit.  Adding to the website is an explicit recommendation to the community, and I think we should be judicious about that.  As it stands, this page lists some middleware which should be audited IMO.

**Comment by crandmck** [comment]
I agree with @wesleytodd.  I think we should err on the side of caution... I don't recall where that set of middleware came from (probably some README), but I think it might be worth reviewing it again, and we could include this PR as a potential addition.

**Comment by ameerthehacker** [comment]
@crandmck If my understanding is right my middleware will go through a reviewing process and then this PR will be considered for merging. If so how the reviewing process is going to be?

**Comment by crandmck** [comment]
>  If so how the reviewing process is going to be?

@ameerthehacker It's a fair question.  We haven't established one yet.  

If and when we do establish this process, we should review all the "Additional middleware" (i.e. non-expressjs-maintained modules) listed in https://expressjs.com/en/resources/middleware.html so it's an even playing field.
 
I suggest we keep the process simple and lightweight.  Perhaps simply a discussion issue? @wesleytodd Thoughts?

**Comment by ameerthehacker** [comment]
Hey @crandmck @wesleytodd any updates on this discussion?

**Comment by crandmck** [comment]
Sorry for the delay.   We should probably have some kind of criteria or process for inclusion on the site...  Unfortunately, establishing it will take some time.  We're going to get more requests like this, and in fact we already did -- see #981.  

I started #988 to discuss this issue more generally. 

@ameerthehacker I'm afraid resolution of this particular PR will have to wait until the more general issue is resolved.  Thanks for your patience.

**Comment by dougwilson** [comment]
So with the discussion here being controversial, and I guess this section is noted "These are some additional popular middleware modules" while this module as (currently) zero weekly downloads according to npm, I guess I won't land it 😢 . It does seem well made, though.

**Pull request closed without merging**
