### PR TITLE
fix nav links do not reappear after resizing

### LINKED ISSUE #1499: Nav links do not reppear after resizing
If while at the `@media (max-width: 899px)` breakpoint the `<div id="mobile-menu">` hamburger  menu is opened and then closed, then the screen is enlarged, the nav bar links to do reappear. 

https://github.com/expressjs/expressjs.com/assets/14151974/fd50b225-51ad-447d-a136-e26bc3172ea5

### PR DESCRIPTION
**Pull request by aastha-cse**
Fixes #1499

The issue was with the toggling of display style between navmenu and overlay. To solve this I  added a new class name 'open' that fixes the problem.

https://github.com/expressjs/expressjs.com/assets/100745494/f874cac4-d955-408c-8624-fc78cf2c327f

### CODE REVIEW

**Comment by crandmck** [comment]
@chrisdel101 Is this affected at all by your recent dark mode changes, or vice-versa?  
And do you have any comments in general on these changes, even though they seem quite simple.... since you've been working in the CSS and JS / layout code recently, I thought I'd just check with you.

**Comment by chrisdel101** [comment]
So I noticed this issue when I was working on that feature, but I recall I switched back to main (`gh-pages` branch) and this problem was occurring there as well. So I'm pretty sure I did not cause it. It seemed to be there already. Just wanted to report on this.
Will report in on the PR changes soon.

**Comment by jonchurch** [comment]
clopened to  see if it will trigger a build preview

**Comment by jonchurch** [comment]
I honestly don't know why this works but it does

**Comment by jonchurch** [comment]
Ahh, the overlay is staying open after resizing the page, leaving an opacity layer over the top of the page

Screenshot 2024-05-03 at 8 12 04 PM

We should find a way to achieve all of this via media queries.

**Comment by aastha-cse** [comment]
I looked into the overlay issue and fixed it using the same method that i used to fix the nav bar. It was working fine on my local system but I can't figure out the reason of 'deploy fail'.


https://github.com/expressjs/expressjs.com/assets/100745494/b6871ab1-e2a5-4ee1-8702-11894bef6d6d

**Comment by crandmck** [comment]
The build is failing because Netlify is trying to use Jekyll build dependencies' README files, and at least one  README has a malformed liquid directive:

```
Liquid Exception: Liquid syntax error (line 50): Variable '{{a}' was not properly terminated with regexp: /\}\}/ in node_modules/balanced-match/README.md
```

This should be fixed by https://github.com/expressjs/expressjs.com/pull/1510 ... @aastha-cse Can you get the changes from that PR so we can preview this one?

**Comment by chrisdel101** [comment]
> We should find a way to achieve all of this via media queries.

@jonchurch I'm seeing the media queries for the `#navmenu` . Which parts did you have in mind that could be fixed up?

**Comment by crandmck** [comment]
This is building now and the preview looks OK to me.... @jonchurch Do we need further changes or can we land this?

**Review by crandmck — APPROVED** [review]

**Pull request merged**
