### PR TITLE
Replace tags with backticks, and other changes

### PR DESCRIPTION
**Pull request by crandmck**
This includes all the changes noted in #597.  I decided to make the change to code blocks only for English pages.  I left all translated (non-en) pages "as is" with `<pre><code> ...` tags instead of backticks.

### CODE REVIEW

**Comment by hacksparrow** [comment]
Looks good. Has GitHub fixed the backtick issue?

**Comment by hacksparrow** [comment]
I just checked. The backtick behavior is still in the "broken" state. If this PR is merged, we will lose the current code highlighting. We will need additional work to save the code highlighting.

**Comment by crandmck** [comment]
@hacksparrow Obviously we don't want to do this if it breaks code highlighting.

I was told that it was fixed by the GitHub employee who opened the PR with these very changes against `express-api-docs` quite some time ago.  Unfortunately, I deleted that repo (since it was redundant) so I don't have the specific issue/comment.  

I thought that the changes to `_config.yml` were sufficient to fix it.  I'll investigate further.
BTW, how did you test it?

**Comment by hacksparrow** [comment]
What's there in `_config.yml` that it will solve the problem?

I tested it on http://hacksparrow.github.io/git-experiments/. Look at the source code, GitHub tries to do it's own highlighting using Rouge, completely breaking how we expect the code to be.

**Comment by crandmck** [comment]
> What's there in _config.yml that it will solve the problem?

I believe it was this:

```
syntax_highlighter_opts:
    disable : true
```

Should I try to create an demo repo such as yours to ensure that it will work?

**Comment by hacksparrow** [comment]
Ok, I will take a look at it tomorrow, and merge this, if everything looks fine.

**Comment by crandmck** [comment]
OK, thanks!

**Comment by hacksparrow** [comment]
```
syntax_highlighter_opts:
    disable : true
```

make no difference. I wonder what I correct directive is. Tried searching "jekyll _config.yml disable syntax highlight" and the variants, no success.

**Comment by crandmck** [comment]
@hacksparrow I created a test site, and everything (including syntax highlighting) seems to be working OK: http://crandmck.github.io/

Source repo: https://github.com/crandmck/crandmck.github.io.

NOTE: This test site does not include the translations, just to make it a lot smaller :-)

NOTE2: I'll remove this test site content once we've merged this PR and resolved this issue.  It's just temporary for testing.

Perhaps you missed something...?  Did you use the entire `_config.yml` file:

```
# Site settings

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true
```

**Comment by hacksparrow** [comment]
I had `syntax_highlighter_opts` at the root level, hence it had no affect.

Confirmed to be all good, merging this.

**Comment by crandmck** [comment]
Thanks @hacksparrow !
Sorry I wasn't clearer about where `syntax_highlighter_opts` went.

**Pull request merged**
