### PR TITLE
Updating dependencies section of security docs

### PR DESCRIPTION
**Pull request by tkadlec**
For the secure dependencies section, I saw `requireSafe` was still mentioned, but that's been rolled into NSP for awhile (https://twitter.com/requiresafe/status/661228477689950208) so I removed that. 

Replaced it with brief docs about using the [Snyk](https://www.npmjs.com/package/snyk) CLI and DB.

### CODE REVIEW

**Comment by dougwilson** [comment]
Snyk and NSP still seem to host different advisories. Can we list both of them, instead of only Snyk?

**Comment by dougwilson** [comment]
Sorry, misread the comment. The PR LGTM

**Review by dougwilson — APPROVED** [review]

**Comment by crandmck** [comment]
Yes, LGTM. Thanks @tkadlec !

**Comment by tkadlec** [comment]
No problem. Thanks for the super quick turnaround. :)

**Pull request merged**
